routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('report', 'ReportController@index')->name('report');
//Permisos de Usuarios
Route::get('/permissions/{id}', 'UserController@permissions')->name('user.permissions');
Route::put('/permissions/{id}', 'UserController@update_permissions')
    ->name('user.update_permissions');
//Fin de Usuarios
//tableros
Route::get('index_board', 'BoardController@index')->name('index_board');
Route::get('create_board', 'BoardController@create')->name('create_board');
Route::post('create_board', 'BoardController@store')->name('board.store');
Route::get('/edit_board/{id}', 'BoardController@edit')->name('edit_board');
Route::get('/edit_board_public/{id}', 'BoardController@edit_public')->name('edit_board_public');
Route::get('/edit_superv_board/{user_id},{board_id}', 'BoardController@edit_superv')->name('edit_superv_board');
Route::put('/edit_board/{id}', 'BoardController@update')
    ->name('board.update');
Route::delete('/index_board/{id}', 'BoardController@destroy')->name('destroy_board');
Route::get('/qr_board/{id}', 'BoardController@qr')->name('qr_board');
//Archive
Route::get('index_archive', 'Archive_publicController@index')->name('index_archive');
//Route::post('/edit_archive/{id}', 'Archive_publicController@edit')->name('edit_archive');
Route::get('edit_archive', 'Archive_publicController@create')->name('edit_archive');
Route::put('/edit_archive/{id}', 'Archive_publicController@update')->name('update_archive');
//fin archive
//fin tableros
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use jeremykenedy\LaravelRoles\Traits\HasRoleAndPermission;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    //use HasRoleAndPermission;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname','email', 'password','role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Rol;
use App\Roleusers;
use App\Http\Requests\UserRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        return view('users.index', ['users' => $model->paginate(15)]);
    }

    public function permissions($id)
    {
        //dd($id);

         $roles = Roleusers::where('user_id', $id)->get();
         $users = User::where('id', $id)->get();
      //   $rol_id = Rol::where('id', $id)->get();
        // dd($rol_id);
         foreach ($roles as $key => $value) {
            $id = $value->id;
            $role_id = $value->role_id;
          }
        foreach ($users as $key => $value) {
            $obtain = $value->id;
          }
      /* foreach ($rol_id as $key => $value) {
            $obtain_rol = $value->id;
          }*/
       // dd($obtain);
        return view('users.permissions', compact('id','roles','obtain','users','role_id'));
    }
     public function update_permissions(Request $request, $id)
    {
        //dd($request->all());
        $rolemodel = Roleusers::find($id);
        $rolemodel->create_user = $request->create_user;
        $rolemodel->edit_user = $request->edit_user;
        $rolemodel->delete_user = $request->delete_user;
        $rolemodel->permission_user = $request->permission_user;
        $rolemodel->create_board = $request->create_board;
        $rolemodel->edit_board = $request->edit_board;
        $rolemodel->delete_board = $request->delete_board;
        $rolemodel->permission_board = $request->permission_board;
        $rolemodel->bulk_load = $request->bulk_load;
        $rolemodel->hse_board = $request->hse_board;
        $rolemodel->ing_board = $request->ing_board;
        $rolemodel->mant_board = $request->mant_board;
        $rolemodel->cal_board = $request->cal_board;
        $rolemodel->serv_board = $request->serv_board;
        $rolemodel->save();

        return redirect()->route('user.index')->withStatus(__('Permisos actualizado con éxito.'));
    }

    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $roles = Rol::all();
        return view('users.create', compact('roles'));

    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, User $model)
    {
        $user = new User;
        $user->name = $request->name;
        $user->surname = $request->surname;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->role_id = $request->role_id;
        $user->save();
        //dd($user->id);
        $obt = Roleusers::create([
            'role_id' =>$request->role_id,
            'user_id' =>$user->id,
            'create_user' =>'0',
            'edit_user'=>'0',
            'delete_user'=>'0',
            'permission_user'=>'0',
            'create_board'=>'0',
            'edit_board'=>'0',
            'delete_board'=>'0',
            'permission_board'=>'0',
            'bulk_load'=>'0',
            'hse_board'=>'0',
            'ing_board'=>'0',
            'mant_board'=>'0',
            'cal_board'=>'0',
            'serv_board'=>'0'
            ]);

        return redirect()->route('user.index')->withStatus(__('Usuario creado con éxito.'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, User  $user)
    {
         //dd($request->all());
        $user->update([
            'name' => $request->name,
            'surname' => $request->surname,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);
        /*$user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password']
        ));

        $obt = Roleusers::create([
              'role_id' =>$request->role_id,
              'user_id' =>$user->id
            ]);*/
        return redirect()->route('user.index')->withStatus(__('Usuario actualizado con éxito.'));
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User  $user)
    {
        $user->delete();

        return redirect()->route('user.index')->withStatus(__('Usuario eliminado con éxito.'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'titlePage' => __('Gestión de usuarios')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('user.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Agregar Usuario') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a la lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Nombre') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Nombre') }}" value="{{ old('name') }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                   <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Apellidos') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('surname') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" name="surname" id="input-name" type="text" placeholder="{{ __('Apellidos') }}" value="{{ old('surname') }}" required="true" aria-required="true"/>
                      @if ($errors->has('surname'))
                        <span id="surname-error" class="error text-danger" for="input-name">{{ $errors->first('surname') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Correo Electronico') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" id="input-email" type="email" placeholder="{{ __('Correo Electronico') }}" value="{{ old('email') }}" required />
                      @if ($errors->has('email'))
                        <span id="email-error" class="error text-danger" for="input-email">{{ $errors->first('email') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label" for="input-password">{{ __(' Contraseña') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" input type="password" name="password" id="input-password" placeholder="{{ __('Contraseña') }}" value="" required />
                      @if ($errors->has('password'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('password') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label" for="input-password-confirmation">{{ __('Confirmar Contraseña') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group">
                      <input class="form-control" name="password_confirmation" id="input-password-confirmation" type="password" placeholder="{{ __('Confirmar Contraseña') }}" value="" required />
                    </div>
                  </div>
                </div>
                <div class="row">
                <label class="col-sm-2 col-form-label" for="">{{ __('Perfil') }}</label>
                 @if (Auth::user()->role_id == 1)
                <div class="col-sm-7">
                    <div class="form-group">
                      <select class="form-control" id="role_id" name="role_id" required>
                         <option value="">
                      Seleccione
                    </option>
                    @foreach ($roles as $rol)
                    <option value="{{$rol->id }}">
                      {{ $rol->name}}
                    </option>
                    @endforeach
                  </select>
                    </div>
                  </div>
                  @endif
                    @if (Auth::user()->role_id == 2)
                <div class="col-sm-7">
                    <div class="form-group">
                      <select class="form-control" id="role_id" name="role_id" required>
                         <option value="">
                      Seleccione
                    </option>
                    <option value="3">Supervisor</option>
                  </select>
                    </div>
                  </div>
                  @endif
              </div>

              </div><!--fin-->
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Agregar Usuario') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection
<script>
$(document).ready(function() {
    $('.mb-select').material_select();
  });
</script>

resources/views/users/edit.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'titlePage' => __('Gestión de usuarios')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('user.update', $user) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Editar Usuario') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a la Lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Nombre') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Nombre') }}" value="{{ old('name', $user->name) }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                  <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Apellidos') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('surname') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" name="surname" id="input-name" type="text" placeholder="{{ __('Apellidos') }}" value="{{ old('name', $user->surname) }}" required="true" aria-required="true"/>
                      @if ($errors->has('surname'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('surname') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Correo Electronico') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" id="input-email" type="email" placeholder="{{ __('Correo Electronico') }}" value="{{ old('email', $user->email) }}" required />
                      @if ($errors->has('email'))
                        <span id="email-error" class="error text-danger" for="input-email">{{ $errors->first('email') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label" for="input-password">{{ __(' Contraseña') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" input type="password" name="password" id="input-password" placeholder="{{ __('Contraseña') }}" />
                      @if ($errors->has('password'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('password') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label" for="input-password-confirmation">{{ __('Confirmar Contraseña') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group">
                      <input class="form-control" name="password_confirmation" id="input-password-confirmation" type="password" placeholder="{{ __('Confirmar Contraseña') }}" />
                    </div>
                  </div>
                </div>

              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Guardar') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'titlePage' => __('Gestión de usuarios')])
 <script type="text/javascript">
    (function(document) {
      'use strict';

      var LightTableFilter = (function(Arr) {

        var _input;

        function _onInputEvent(e) {
          _input = e.target;
          var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
          Arr.forEach.call(tables, function(table) {
            Arr.forEach.call(table.tBodies, function(tbody) {
              Arr.forEach.call(tbody.rows, _filter);
            });
          });
        }

        function _filter(row) {
          var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
          row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
        }

        return {
          init: function() {
            var inputs = document.getElementsByClassName('light-table-filter');
            Arr.forEach.call(inputs, function(input) {
              input.oninput = _onInputEvent;
            });
          }
        };
      })(Array.prototype);

      document.addEventListener('readystatechange', function() {
        if (document.readyState === 'complete') {
          LightTableFilter.init();
        }
      });

    })(document);
    </script>
@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Usuarios') }}</h4>
                <p class="card-category"> {{ __('Aquí puedes administrar usuarios') }}</p>
              </div>
              <br>
               <div class="row">
                  <div class="col-12 text-right">
                    <input class="form-control col-md-3 light-table-filter" style="display: inline;" data-table="order-table" type="text" placeholder="Buscar" title="Presione Esc para supender la búsqueda">
                  </div>
                </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">Cerrar</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row">
                  <div class="col-12 text-right">
                    <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">{{ __('Agregar Usuario') }}</a>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table  order-table">
                     @if (Auth::user()->role_id == 1)
                    <thead class="text-primary">
                      <th>
                          {{ __('Nombre') }}
                      </th>
                       <th>
                          {{ __('Apellidos') }}
                      </th>
                      <th>
                        {{ __('Correo Electronico') }}
                      </th>
                      <th>
                        {{ __('Permisos') }}
                      </th>
                      <th class="text-right">
                        {{ __('Acción') }}
                      </th>
                    </thead>
                    <tbody id="user">
                      @foreach($users as $user)
                        <tr>
                          <td>
                            {{ $user->name }}
                          </td>
                          <td>
                            {{ $user->surname }}
                          </td>
                          <td>
                            {{ $user->email }}
                          </td>
                          <td>
                            @if($user->id == 1)

                            @else
                               <a rel="tooltip" class="btn btn-warning btn-link" href="{{ route('user.permissions', $user) }}" data-original-title="" title="">
                                <i class="material-icons">vpn_key</i>
                                <div class="ripple-container"></div>
                              </a>
                              @endif
                          </td>

                          <td class="td-actions text-right">
                              <form action="{{ route('user.destroy', $user) }}" method="post">
                                  @csrf
                                  @method('delete')
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('user.edit', $user) }}" data-original-title="">
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <button type="button" class="btn btn-danger btn-link" data-original-title="" title="Eliminar Usuario" onclick="confirm('{{ __("Estás seguro de que deseas eliminar a este usuario?") }}') ? this.parentElement.submit() : ''">
                                      <i class="material-icons">delete</i>
                                      <div class="ripple-container"></div>
                                  </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                      @endif
                      @if (Auth::user()->role_id == 2)
                    <thead class=" text-primary">
                      <th>
                          {{ __('Nombre') }}
                      </th>
                       <th>
                          {{ __('Apellidos') }}
                      </th>
                      <th>
                        {{ __('Correo Electronico') }}
                      </th>
                      <th>
                        {{ __('Permisos') }}
                      </th>
                      <th class="text-right">
                        {{ __('Acción') }}
                      </th>
                    </thead>
                    <tbody id="user">
                      @foreach($users as $user)
                        <tr>
                        @if($user->role_id ==2 or $user->role_id==3)
                          <td>
                            {{ $user->name }}
                          </td>
                          <td>
                            {{ $user->surname }}
                          </td>
                          <td>
                            {{ $user->email }}
                          </td>
                          <td>
                            {{-- $user->created_at->format('Y-m-d') --}}
                                <a rel="tooltip" class="btn btn-warning btn-link" href="{{ route('user.permissions', $user) }}" data-original-title="" title="">
                                <i class="material-icons">vpn_key</i>
                                <div class="ripple-container"></div>
                              </a>
                          </td>

                          <td class="td-actions text-right">
                              <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('profile.edit') }}" data-original-title="" >
                                <i class="material-icons">edit</i>
                                <div class="ripple-container"></div>
                              </a>
                          </td>
                          @endif
                        </tr>
                      @endforeach
                      @endif
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  @endsection